[2022-05-22 01:22:30,177] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx manual__2022-05-22T01:13:21.300089+00:00 [queued]>
[2022-05-22 01:22:30,186] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx manual__2022-05-22T01:13:21.300089+00:00 [queued]>
[2022-05-22 01:22:30,186] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 01:22:30,186] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-05-22 01:22:30,186] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 01:22:30,199] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_in_xlsx> on 2022-05-22 01:13:21.300089+00:00
[2022-05-22 01:22:30,203] {standard_task_runner.py:52} INFO - Started process 823 to run task
[2022-05-22 01:22:30,205] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Teste_ETL_Raízen', 'convert_xls_in_xlsx', 'manual__2022-05-22T01:13:21.300089+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpfvfvuzng', '--error-file', '/tmp/tmpzpxw3rha']
[2022-05-22 01:22:30,206] {standard_task_runner.py:80} INFO - Job 23: Subtask convert_xls_in_xlsx
[2022-05-22 01:22:30,249] {task_command.py:369} INFO - Running <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx manual__2022-05-22T01:13:21.300089+00:00 [running]> on host 0a31d31582dc
[2022-05-22 01:22:30,327] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Teste_ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_in_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-05-22T01:13:21.300089+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-22T01:13:21.300089+00:00
[2022-05-22 01:22:30,714] {python.py:173} INFO - Done. Returned value was: None
[2022-05-22 01:22:30,726] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Teste_ETL_Raízen, task_id=convert_xls_in_xlsx, execution_date=20220522T011321, start_date=20220522T012230, end_date=20220522T012230
[2022-05-22 01:22:30,778] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-22 01:22:30,816] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
