[2022-05-19 03:30:02,188] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.captura_conta_dados scheduled__2022-05-19T02:30:00+00:00 [queued]>
[2022-05-19 03:30:02,199] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.captura_conta_dados scheduled__2022-05-19T02:30:00+00:00 [queued]>
[2022-05-19 03:30:02,200] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 03:30:02,201] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-19 03:30:02,201] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 03:30:02,218] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): captura_conta_dados> on 2022-05-19 02:30:00+00:00
[2022-05-19 03:30:02,224] {standard_task_runner.py:52} INFO - Started process 3632 to run task
[2022-05-19 03:30:02,228] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Teste_ETL_Raízen', 'captura_conta_dados', 'scheduled__2022-05-19T02:30:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpkca0g1q5', '--error-file', '/tmp/tmpylcfwr39']
[2022-05-19 03:30:02,230] {standard_task_runner.py:80} INFO - Job 11: Subtask captura_conta_dados
[2022-05-19 03:30:02,295] {task_command.py:369} INFO - Running <TaskInstance: Teste_ETL_Raízen.captura_conta_dados scheduled__2022-05-19T02:30:00+00:00 [running]> on host c8caf9da75ac
[2022-05-19 03:30:02,378] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Teste_ETL_Raízen
AIRFLOW_CTX_TASK_ID=captura_conta_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-05-19T02:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-19T02:30:00+00:00
[2022-05-19 03:30:03,955] {python.py:173} INFO - Done. Returned value was: 807
[2022-05-19 03:30:04,004] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Teste_ETL_Raízen, task_id=captura_conta_dados, execution_date=20220519T023000, start_date=20220519T033002, end_date=20220519T033004
[2022-05-19 03:30:04,051] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-19 03:30:04,118] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
