[2022-05-22 03:01:05,074] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx manual__2022-05-22T02:35:48.168632+00:00 [queued]>
[2022-05-22 03:01:05,082] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx manual__2022-05-22T02:35:48.168632+00:00 [queued]>
[2022-05-22 03:01:05,082] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 03:01:05,082] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-22 03:01:05,082] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 03:01:05,095] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_in_xlsx> on 2022-05-22 02:35:48.168632+00:00
[2022-05-22 03:01:05,099] {standard_task_runner.py:52} INFO - Started process 655 to run task
[2022-05-22 03:01:05,101] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Teste_ETL_Raízen', 'convert_xls_in_xlsx', 'manual__2022-05-22T02:35:48.168632+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmp3ia8du_d', '--error-file', '/tmp/tmpx44uhzmv']
[2022-05-22 03:01:05,102] {standard_task_runner.py:80} INFO - Job 45: Subtask convert_xls_in_xlsx
[2022-05-22 03:01:05,142] {task_command.py:369} INFO - Running <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx manual__2022-05-22T02:35:48.168632+00:00 [running]> on host de43a65d8e31
[2022-05-22 03:01:05,201] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Teste_ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_in_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-05-22T02:35:48.168632+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-22T02:35:48.168632+00:00
[2022-05-22 03:01:08,172] {python.py:173} INFO - Done. Returned value was: None
[2022-05-22 03:01:08,185] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Teste_ETL_Raízen, task_id=convert_xls_in_xlsx, execution_date=20220522T023548, start_date=20220522T030105, end_date=20220522T030108
[2022-05-22 03:01:08,204] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-22 03:01:08,241] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
